const ADMIN_LOGIN="ADMIN_LOGIN";
const ADMIN_REMOVE="ADMIN_REMOVE";
const ADMIN_LIST="ADMIN_LIST";

const USER_TOTAL = "USER_TOTAL";
const USER_LIST = "USER_LIST";
const PAGE_NO = "PAGE_NO";
const USER_LIKE = "USER_LIKE";



export default {
	ADMIN_LOGIN,
	ADMIN_REMOVE,
	ADMIN_LIST,
	USER_TOTAL,
	USER_LIST,
	PAGE_NO,
	USER_LIKE
}